stages:
    - build
    - deployment

build:
    stage: build
    image: docker
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER  -p ${CI_CD_PASSWORD} $CI_REGISTRY_IMAGE
        - docker build -t $CI_REGISTRY_IMAGE .
        - docker push $CI_REGISTRY_IMAGE
        - docker logout