stages:
    - build
    - deployment

# build:
#     stage: build
#     image: docker
#     services:
#         - docker:dind
#     script:
#         - docker login -u $CI_REGISTRY_USER  -p ${CI_CD_PASSWORD} $CI_REGISTRY_IMAGE
#         - docker build -t $CI_REGISTRY_IMAGE .
#         - docker push $CI_REGISTRY_IMAGE
#         - docker logout
#     only:
#     - tags

deploy:
    stage: deployment
    image: alpine
    before_script:
        - apk add openssh-client
        - eval $(ssh-agent -s)
        - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
    script:
         - ssh -o StrictHostKeyChecking=no root@194.195.118.85 "cd / && "sudo docker pull registry.gitlab.com/hotelierpro/ui-library && sudo docker stop ui-library || true && sudo docker rm ui-library || true &&sudo docker run -d --name ui-library -p 3000:3000 registry.gitlab.com/hotelierpro/ui-library"


# npm:
#     stage: publish-npm
#     script:
#         - echo "//registry.npmjs.org/:_authToken=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" > .npmrc && npm publish
#     only:
#     - master
#     - tags
