stages:
    - build
    - deployment
    - publish-npm

build:
    stage: build
    image: docker
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER  -p ${CI_CD_PASSWORD} $CI_REGISTRY_IMAGE
        - docker build -t $CI_REGISTRY_IMAGE .
        - docker push $CI_REGISTRY_IMAGE
        - docker logout
npm:
    stage: publish-npm
    script:
        - echo "//registry.npmjs.org/:_authToken=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" > .npmrc && npm publish
    only:
    - master
